x-logging: &logging
  logging:
    options:
      max-size: 10m
      max-file: "24"

services:
  raiko:
    <<: *logging
    build:
      context: src/raiko
      dockerfile: Dockerfile
    image: ${RAIKO_SN_RAIKO_IMAGE:-raiko}:${RAIKO_SN_RAIKO_IMAGE_TAG:-latest}
    restart: unless-stopped
    command: --config-path=/etc/raiko/config.sgx.json --chain-spec-path=/etc/raiko/chain_spec_list.docker.json
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - ./data/logs/raiko:/var/log/raiko
      - ./data/gramine:/root/.config/gramine
      - ./data/raiko:/root/.config/raiko
    ports:
      - "${RAIKO_SN_RAIKO_PORT:-8080}:8080"
    environment:
      - SGX=true
      - SGX_DIRECT=${RAIKO_SN_SGX_DIRECT:-0}
      - SGX_INSTANCE_ID=${RAIKO_SN_INSTANCE_ID:-}
      - ETHEREUM_RPC=${RAIKO_SN_ETHEREUM_RPC:-}
      - ETHEREUM_BEACON_RPC=${RAIKO_SN_ETHEREUM_BEACON_RPC:-}
      - HOLESKY_RPC=${RAIKO_SN_HOLESKY_RPC:-}
      - HOLESKY_BEACON_RPC=${RAIKO_SN_HOLESKY_BEACON_RPC:-}
      - TAIKO_A7_RPC=${RAIKO_SN_TAIKO_A7_RPC:-}
      - TAIKO_MAINNET_RPC=${RAIKO_SN_TAIKO_MAINNET_RPC:-}
      - L1_NETWORK=${RAIKO_SN_L1_NETWORK:-}
      - NETWORK=${RAIKO_SN_NETWORK:-}
    depends_on:
      - pccs

  pccs:
    <<: *logging
    build:
      context: src/raiko
      dockerfile: Dockerfile.pccs
    image: ${RAIKO_SN_PCCS_IMAGE:-pccs}:${RAIKO_SN_PCCS_IMAGE_TAG:-latest}
    restart: unless-stopped
    volumes:
      - ./data/pccs/default.json:/opt/intel/pccs/config/default.json
      - ./data/pccs/file.crt:/opt/intel/pccs/ssl_key/file.crt
      - ./data/pccs/private.pem:/opt/intel/pccs/ssl_key/private.pem

  prometheus:
    <<: *logging
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./src/raiko/docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "${RAIKO_SN_PROMETHEUS_PORT:-9090}:9090"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - metrics

  grafana:
    <<: *logging
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "${RAIKO_SN_GRAFANA_PORT:-3000}:3000"
    volumes:
      - ./data/grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    profiles:
      - metrics

volumes:
  grafana: {}
  prometheus: {}
