services:
  raiko:
    build:
      context: src/raiko
      dockerfile: Dockerfile
    image: ${SRN_RAIKO_IMAGE:-raiko}:${SRN_IMAGES_TAG:-latest}
    restart: unless-stopped
    command: --config-path=/etc/raiko/config.sgx.json --chain-spec-path=/etc/raiko/chain_spec_list.docker.json
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - ./data/logs/raiko:/var/log/raiko
      - ./data/gramine:/root/.config/gramine
      - ./data/raiko:/root/.config/raiko
    ports:
      - "${SRN_RAIKO_PORT:-8080}:8080"
    environment:
      - SGX_DIRECT=${SRN_SGX_DIRECT:-0}
      - SGX_INSTANCE_ID=${SRN_INSTANCE_ID}
      - L1_NETWORK=${SRN_L1_NETWORK}
      - NETWORK=${SRN_NETWORK}
      - ETHEREUM_RPC=${SRN_ETHEREUM_RPC}
      - ETHEREUM_BEACON_RPC=${SRN_ETHEREUM_BEACON_RPC}
      - HOLESKY_RPC=${SRN_HOLESKY_RPC}
      - HOLESKY_BEACON_RPC=${SRN_HOLESKY_BEACON_RPC}
      - TAIKO_A7_RPC=${SRN_TAIKO_A7_RPC}
      - TAIKO_MAINNET_RPC=${SRN_TAIKO_MAINNET_RPC}
    depends_on:
      - pccs

  pccs:
    build:
      context: src/raiko
      dockerfile: Dockerfile.pccs
    image: ${SRN_PCCS_IMAGE:-pccs}:${SRN_IMAGES_TAG:-latest}
    restart: unless-stopped
    volumes:
      - ./data/pccs/default.json:/opt/intel/pccs/config/default.json
      - ./data/pccs/file.crt:/opt/intel/pccs/ssl_key/file.crt
      - ./data/pccs/private.pem:/opt/intel/pccs/ssl_key/private.pem

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./src/raiko/docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "${SRN_PROMETHEUS_PORT:-9090}:9090"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - metrics

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "${SRN_GRAFANA_PORT:-3000}:3000"
    volumes:
      - ./data/grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    profiles:
      - metrics

volumes:
  grafana:
  prometheus:
